Feature/slider
DanyaKingSize/Aldera_test pull request #3
Opened 2024-04-03 13:55 UTC by DanyaKingSize

2024-04-03 13:57 UTC, TokinNik commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +            throw Exception('Error type in Media Player');
Лучше показывать ошибку текстом на экране. Эту ошибку никто не ловит, бесполезна.

2024-04-04 07:52 UTC, TokinNik requested changes

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_bloc.dart
> +    on<GetMediaDetailEvent>((event, emit) async {
Вынести обработчики ивентов в отдельные методы. ### on\<SomeEvent>(_someEventHandler)
Также сделать для другого блока

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_bloc.dart
> +      emit(LoadingDetailState());
Ивент загрузки должен идти до долгих операций. Тут это получение ссылки на видео.

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_description.dart
> +          style: const TextStyle(
Вынести все стили в константные ресурсы. В отдельный файл

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_description.dart
> +            color: Colors.white,
Цвета тоже вынести

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_description.dart
> +            'Description',
Почитать про slang либу для флаттера и подключить её. Заменить все строки на константы slang

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/detail_screen.dart
> +      backgroundColor: const Color.fromRGBO(31, 31, 31, 1),
Цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +          if (state is SuccessMediaDetailState) {
Добавить тут обработку других состояний блока (Idle, Loading)

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +        listener: (context, state) {
Вынести листенер в отдельный метод

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +        builder: (context, state) {
Вынести билдер в отдельный метод

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +            backgroundColor: const Color.fromRGBO(31, 31, 31, 1),
Цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_request/my_bloc.dart
> +            data: [],
дефолтные значения лучше прописать в конструкторе стейта 
### SomeState({required this.someFieldList = const []})

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_request/my_bloc.dart
> +      (event, emit) async {
Вынести в отдельные методы

2024-04-04 07:52 UTC, TokinNik commented on lib/feature/detail/Bloc_request/my_bloc.dart
> +            dateFilters: state.filtersData);
запятая

2024-04-04 07:52 UTC, TokinNik commented on lib/home/filters/filter_bottom.dart
> +          backgroundColor: const Color.fromRGBO(34, 35, 41, 1),
Цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/home/filters/my_bottom_sheet.dart
> +                style: TextStyle(color: Colors.white, fontSize: 24),
Стили, цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/home/filters/slider.dart
> +                      style: const TextStyle(
Стили, цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/home/image_card.dart
> +        color: Colors.grey[800],
Стили, цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/home/my_button.dart
> +                  color: Colors.deepPurple,
Цвета

2024-04-04 07:52 UTC, TokinNik commented on lib/home/my_grid_view.dart
> +                      throw Exception('listView Error media type');
Ошибку никто не ловит, лучше найти другое поведение при типу unknown

2024-04-04 07:52 UTC, TokinNik commented on lib/main.dart
> +      backgroundColor: const Color.fromRGBO(34, 35, 41, 1),
Цвета и стили

2024-04-04 07:52 UTC, TokinNik commented on lib/main.dart
>            'assets/appBar.png',
Картинки тоже вынести в отдельные константы

2024-04-04 07:52 UTC, TokinNik commented on lib/repository/api_request_service.dart
> +    return 'https://images-api.nasa.gov/asset/$nasaId'; // fixme base url to constant
Вынести базовый урл

2024-04-08 13:15 UTC, TokinNik requested changes
Самый лучший проект который я видел

2024-04-08 13:17 UTC, DanyaKingSize commented on lib/feature/detail/Bloc_media/video_player_screen.dart
> +            throw Exception('Error type in Media Player');
+

2024-04-08 13:23 UTC, merged